# .github/workflows/test.yml

name: Pytest + Report

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-json-report

    - name: Run tests and generate JSON report
      run: |
        pytest --json-report --json-report-file=report.json

    - name: Generate Markdown summary
      run: |
        python scripts/generate_md_summary.py report.json > test-report.md

    - name: Upload report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-markdown-report
        path: test-report.md
